// <auto-generated />
using LibraryManagerMVC_2212447.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagerMVC_2212447.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250821075812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("LibraryManagerMVC_2212447.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Nguyễn Văn A",
                            CategoryId = 3,
                            ISBN = "978-123456789",
                            PublishedYear = 2023,
                            Title = "Lập trình C# cơ bản"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Nguyễn Du",
                            CategoryId = 2,
                            ISBN = "978-987654321",
                            PublishedYear = 1820,
                            Title = "Truyện Kiều"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Trần Văn B",
                            CategoryId = 1,
                            ISBN = "978-111222333",
                            PublishedYear = 2022,
                            Title = "Vật lý đại cương"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Lê Thị C",
                            CategoryId = 4,
                            ISBN = "978-444555666",
                            PublishedYear = 2021,
                            Title = "Quản lý dự án"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Phạm Văn D",
                            CategoryId = 5,
                            ISBN = "978-777888999",
                            PublishedYear = 2020,
                            Title = "Lịch sử Việt Nam"
                        });
                });

            modelBuilder.Entity("LibraryManagerMVC_2212447.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Khoa học",
                            Description = "Sách về khoa học và công nghệ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Văn học",
                            Description = "Sách văn học và tiểu thuyết"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "CNTT",
                            Description = "Sách về công nghệ thông tin và lập trình"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Kinh tế",
                            Description = "Sách về kinh tế và quản lý"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Lịch sử",
                            Description = "Sách về lịch sử và văn hóa"
                        });
                });

            modelBuilder.Entity("LibraryManagerMVC_2212447.Models.Book", b =>
                {
                    b.HasOne("LibraryManagerMVC_2212447.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagerMVC_2212447.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
